<template>
  <div class="terms">
    <div class="text-lg text-bold">TÉRMINOS Y CONDICIONES</div><br>
    <div class="text-left">Los siguientes términos y condiciones se aplican a todos los servicios recibidos, así como también al acceso y uso de los sitios web de Milla Travel SpA (en adelante “Milla.Travel”, una sociedad por acciones constituida en conformidad a las leyes de la República de Chile, domiciliada en Presidente Riesco N° 5330, local 206, comuna de Las Condes.</div><br>
    <div class="terms__terms">
      <div><strong>1. ASPECTO GENERALES</strong> Milla.Travel es una agencia de viajes online que intermedia en la contratación de los servicios de las líneas aéreas, hoteles y otros proveedores de servicios de viaje que operan con nosotros. Le informamos acerca de sus características o condiciones, gestionamos sus solicitudes de reservas y compras, recaudamos los valores correspondientes a los precios y le apoyamos en la búsqueda de soluciones cuando se le presenta una inquietud o un inconveniente. Las líneas aéreas, hoteles y otros proveedores de servicios de viaje son quienes transportan y alojan a los usuarios.</div><br>

      <div><strong>2. PRESTACION DE SERVICIOS</strong> Milla Travel no es responsable de la prestación de los servicios de viajes y no garantiza la exactitud de cualquier material, información o resultados puestos a disposición del cliente por o de los proveedores de servicios de viaje. La presentación del inventario de viajes a través de los servicios de suscripción no constituye una oferta de contrato vinculante por Milla.Travel o el respectivo proveedor de servicios de viaje. El cliente reconoce y acepta que (i) la compra de servicios de viaje puede estar sujeta a los términos y condiciones, acuerdos (como el contrato de transporte) y las políticas de privacidad y seguridad del proveedor de servicios de viaje específico seleccionado por el usuario autorizado, y (ii) el uso de los servicios de viaje estará sujeto al cumplimiento por parte del cliente y de los usuarios autorizados de la ley aplicable. El cliente y sus usuarios autorizados serán los únicos responsables y asumirán todos los riesgos derivados de la selección, el uso y la recepción de cualquier servicio de viaje. El cliente será responsable de la precisión de toda la información compartida que proporcione a las transacciones. Milla.Travel no será responsable por el desempeño de ningún servicio de viaje, cualquier pérdida o lesión a un usuario autorizado como resultado de un servicio de viaje, o cualquier uso no autorizado, divulgación o mal uso de cualquier Información compartida por un proveedor de servicios de viaje.</div><br>

      <div><strong>3. ¿CÓMO FUNCIONA EL SERVICIO DE SUSCRIPCIÓN?</strong> Milla.Travel proporcionará un servicio de suscripción según este acuerdo, comenzando en la fecha que el cliente inscribe su primer usuario y continuando hasta el momento en que el cliente cancela la cuenta del empleador o este acuerdo se rescinde de otro modo. El cliente puede acceder y utilizar los servicios de suscripción únicamente para sus fines comerciales internos y dicho acceso y uso se limita expresamente a los usuarios autorizados del cliente. A través de los servicios de suscripción, el cliente y sus usuarios autorizados pueden recibir servicios de terceros proveedores de viajes y servicios relacionados, como aerolíneas, operadores de hoteles, agregadores de inventario de viajes y agencias de viaje. Para facilitar la compra de estos servicios por parte de un usuario autorizado, el cliente y el usuario autorizan a las transacciones a enviar cierta información, incluido el nombre y otra información personal del usuario autorizado y se comprometen a pagar el total del servicio mediante transferencia o tarjeta de crédito, al proveedor de servicios de viaje en la medida requerida por el proveedor.</div><br>

      <div><strong>4. SI CONTRATO POR INTERMEDIO DE MILLA.TRAVEL ¿QUE DEBO PAGAR?</strong> Cuando Ud. contrata un servicio a través de nuestra agencia, Milla.Travel, debe pagar el equivalente a la suma del precio o tarifa del servicio corporativo, más impuestos y tasas (cuando correspondan), y el cargo por el servicio de intermediación de Milla.Travel. De este pago recaudado por Milla.Travel, nuestra agencia solo retiene el valor correspondiente al servicio de intermediación. El precio por el o los servicios pertenece a los proveedores finales. Es importante que antes de aceptar la transacción, preste mucha atención y lea cuidadosamente las informaciones sobre los valores vigentes que le transmite Milla.Travel, antes de instruirnos para procesar su compra. Todas las tarifas se facturarán en CLP o USD, excepto que: a) Se disponga de otro modo en una orden de servicio. b) Con respecto a las tarifas asociadas con la compra de servicios de viaje (por ejemplo, tarifas de reserva), en la moneda local aplicable a la compra de dichos servicios de viaje. En la medida en que se requiera una conversión de moneda, la conversión se realizará en el momento de la compra, al tipo de cambio aplicable en ese momento.</div><br>

      <div><strong>5. ¿COMO FUNCIONA EL PROCESO DE COMPRA Y/O RESERVA?</strong> El proceso inicia con la solicitud de reserva generada por el usuario desde nuestro sitio web. Enviada la solicitud en forma electrónica, el usuario recibirá al mismo correo electrónico informado en la solicitud de reserva, una comunicación donde se le indicará el número de solicitud y se le advertirá que el pago está en proceso de validación o confirmación. Le agradeceremos prestar mucha atención a nuestras comunicaciones posteriores, ya que en éstas le iremos informando sobre los avances y estado de su solicitud. Si la solicitud fuera rechazada, la reserva no podrá prosperar y así se le informará mediante correo electrónico. La gestión de la reserva y/o la confirmación de la compra, dependen del pago íntegro y oportuno del precio y/o tarifa del servicio.</div><br>

      <div><strong>6. ¿CUÁNTO DEMORA EL PROCESAMIENTO DE LA RESERVA?</strong> Los tickets de avión y hotel serán subidos a la plataforma en la sección “Mis Viajes” para disponibilidad del Usuario. Milla.Travel tiene un periodo de 3 días para cumplir con la entrega de dicha orden.</div><br>

      <div><strong>7. ¿QUÉ DOCUMENTACIÓN NECESITO PARA VIAJAR?</strong> El cliente y los usuarios tienen el deber de informarse sobre la documentación que podría necesitar para poder realizar su viaje conforme a lo planeado. Verifique con tiempo si requiere pasaporte, visa, vacunas u otras exigencias de documentos tanto para los países de destino, como los países en tránsito. Si la requiere y no dispone de ella, haga los trámites necesarios para obtenerla con anticipación. A través de los servicios de suscripción, el cliente y sus usuarios autorizados pueden guardar sus documentos de viaje como pasaportes, visas y DNI de sus viajeros corporativos. Los usuarios suscritos como administradores de la cuenta tendrán la posibilidad de acceder a todos los documentos de la empresa y podrán usar sus datos para la reserva de servicios de viaje. Milla.Travel no se hace responsable por el mal uso de estos datos por parte de los usuarios habilitados como administradores.</div><br>

      <div><strong>8. UNA VEZ CONFIRMADA UNA RESERVA ¿PUEDO ANULARLA O CAMBIARLA?</strong> SI LO HAGO ¿TENGO COSTOS ASOCIADOS? Al igual que las condiciones que regulan la prestación de los servicios finales, la forma de proceder y los términos que rigen en caso de anulaciones o cancelaciones por desistimiento o cambio de decisión del consumidor, también son determinadas por los proveedores finales. Revíselas antes de reservar, recuerde que hay servicios que no admiten, cambios, ni anulaciones (cancelaciones) y otros que, si bien podrían admitirlo, condicionan su procedencia al pago de una penalidad. Le hacemos presente que en caso de anulación de reservas confirmadas, el cargo por servicio no está sujeto a reintegro, ya que corresponde a un servicio efectivamente prestado por Milla.Travel, el que es diferente del servicio contratado con el proveedor final.</div><br>

      <div><strong>9. ¿CUALES SON LAS RESTRICCIONES Y REGLAS (REGULACIONES) QUE PODRÍAN AFECTAR A UN PASAJE AEREO?</strong> A continuación le entregamos ejemplos de algunas de las restricciones o reglas que podrían afectar un pasaje aéreo. Sin perjuicio, antes de enviarnos la solicitud de compra o reserva preste atención a las regulaciones de los pasajes de su interés. A. PENALIDADES: Las penalidades por cambios de fecha en tarifas económicas pueden variar según aerolínea y ruta, adicionalmente pueden existir diferencias tarifarias que puede cobrar la aerolínea asociados al cambio requerido. Existen tarifas que no permiten cambio de fecha ni devoluciones por disposición de la línea aérea. Consulte previamente. Adicionalmente, Milla.Travel realiza un cobro por concepto de cargo por servicio por la prestación de sus servicios de intermediación en este cambio. B. CAMBIOS DE RUTA: No están permitidos por las aerolíneas. C. CAMBIO DE NOMBRE: No están permitidos por las líneas aéreas. D. FRANQUICIAS DE EQUIPAJE: Todas las líneas aéreas tienen diferentes políticas de cobro de exceso de equipaje. Infórmese antes de viajar.</div><br>

      <div><strong>10. PROCEDIMIENTO EN CASO DE RECLAMOS.</strong> El siguiente es el procedimiento que seguirá Milla.Travel en caso de reclamo de un consumidor: a) El consumidor podrá enviar su reclamo al correo electrónico reclamos@milla.travel. Se recomienda adjuntar de inmediato la copia de los antecedentes de respaldo, explicando lo ocurrido y formulando en términos claros y simples la solución que desea. De esta manera podremos revisar su caso en forma más rápida y eficiente. b) Milla.Travel analizará el reclamo y dará respuesta al mismo correo electrónico del consumidor dentro de un plazo de 10 días hábiles a contar de la recepción de los antecedentes. En caso de requerir un plazo superior para recopilar antecedentes o más información, le informará al consumidor especificando el plazo adicional. c) Si de la revisión de los antecedentes aparece procedente acoger en todo o parte el reclamo, Milla.Travel así lo informará y le enviará el correspondiente Recibo de Indemnización y Finiquito, con Subrogación, que es el documento donde se dejará constancia de las condiciones del acuerdo y de cesiones de derechos del pasajero o cliente a Milla.Travel a fin que ésta, en caso de corresponder, se dirija contra el que resultare responsable. Lo anterior, sin perjuicio de que Milla.Travel ofrezca al cliente o pasajero una solución alternativa diferente a las peticiones formuladas. d) Si el pasajero o cliente, está de acuerdo con la propuesta de Milla.Travel, deberá firmar el correspondiente Recibo de Indemnización y Finiquito, con Subrogación ante Notario y enviarlo mediante carta certificada a las oficinas de Milla.Travel ubicadas en Presidente Riesco 5330, local 206, Las Condes. Atención: Recibido el documento en las oficinas de Milla.Travel, se le confirmará al cliente o pasajero fecha de pago al correo electrónico informado y se le solicitarán los antecedentes para los efectos de cursar la respectiva transferencia electrónica. e) En caso de reclamos acogidos, total o parcialmente, los gastos de correo y de Notaría son reintegrados por Despegar.com contra presentación del correspondiente recibo, comprobante o boleta. f) El pasajero dispondrá para reclamar bajo este procedimiento, el mismo plazo establecido en el artículo 26 de la Ley de Protección de los Derechos de los Consumidores. Lo anterior sin perjuicio de lo prevenido en el artículo 49 de la ley 20.423 sobre Turismo u otras disposiciones legales que resultaren aplicables.</div><br>

      <div><strong>11. ¿CUÁLES SON MIS OBLIGACIONES CON MILLA.TRAVEL?</strong> El cliente deberá proporcionar apoyo y cooperación en el acceso a los documentos de viaje de los respectivos usuarios e información personal necesaria para concretar un viaje. Con respecto a cualquier dato del cliente que este inscriba en la plataforma, almacene o procese a través del sitio web, el cliente confirma y garantiza que: a) Es el creador y propietario de, o tiene las licencias, derechos, consentimientos y permisos necesarios para usar y autorizar a las transacciones (y, cuando corresponda, usuarios autorizados) para usar y distribuir los datos del cliente según sea necesario para ejercer las licencias otorgadas en este acuerdo. b) Los datos del cliente, y el uso de los mismos, no infringen, violan o malversan ningún derecho de terceros, incluidos los derechos de autor, marca registrada, patente, secreto comercial, derecho moral, derecho de privacidad, derecho de publicidad o cualquier otra propiedad intelectual o derecho de propiedad.</div><br>

      <div><strong>12. RESTRICCIONES</strong> El cliente no debe intentar interferir o interrumpir los servicios de suscripción o el software ni intentar obtener acceso a ningún sistema o red que se conecte a los mismos (excepto según sea necesario para acceder y utilizar los servicios de suscripción). El cliente no debe permitir el acceso o el uso de los servicios de suscripción por parte de nadie que no sea usuarios autorizados. El cliente no deberá, y hará todos los esfuerzos comercialmente razonables para garantizar que sus usuarios autorizados no: (a) copien, modifiquen o distribuyan ninguna parte de los servicios de suscripción o software; (b) alquilen, arrienden o proporcionen acceso a los servicios de suscripción en base a tiempo compartido u oficina de servicios; o (c) transfieran cualquiera de sus derechos en virtud del presente.</div><br>

      <div><strong>13. POLITICAS DE USO</strong> El cliente utilizará los servicios de suscripción exclusivamente para fines autorizados y legales, de conformidad con todas las leyes, reglamentos y derechos de terceros aplicables. El cliente no puede, y se asegurará de que los usuarios autorizados no utilicen los servicios de suscripción de ninguna manera que viole los derechos de un tercero, incluido, entre otros, el almacenamiento o procesamiento de información confidencial, personal o de pago de terceros en el servicios de suscripción sin la licencia legal adecuada o permiso para hacerlo. El cliente deberá, y se asegurará de que sus usuarios autorizados, se mantengan confidenciales y no revelen a terceros ninguna identificación de usuario, número de cuenta y perfil de cuenta. El usuario será responsable de efectuar el pago de los servicios ya sea con tarjeta de crédito o depósito bancario según la selección que haya escogido en la plataforma.</div><br>

      <div><strong>14. DERECHOS DE PROPIEDAD INTELECTUAL</strong> Todos los contenidos que se muestran en el sitio web, entre ellos, pero no limitado a, artículos, diseños, textos, gráficos, logos, iconos, código en lenguaje, software, marcas o cualesquiera otros signos susceptibles de utilización industrial y/o comercial, están sujetos a derechos de propiedad industrial e intelectual de Milla.Travel o terceros titulares de los mismos que han autorizado debidamente su inclusión en el sitio web, sin que pueda entenderse que el uso y acceso al sitio web y la utilización de sus servicios atribuya al cliente o usuario derecho alguno sobre los citados elementos. Está prohibida la reproducción, explotación, alteración, distribución o comunicación pública del sitoio web para usos diferentes de la legítima información o contratación por los clientes o usuarios de los servicios ofertados.</div><br>

      <div><strong>15. SITIO WEB.</strong> Milla.Travel se reserva la posibilidad de modificar el diseño, presentación y/o configuración de la Página Web, así como algunos o todos los servicios, y añadir servicios nuevos. Asimismo, Milla.Travel se esforzará por mantener la Página Web disponible de la forma más constante posible, reconociendo el usuario que es posible que, por razones de mantenimiento, seguridad o capacidad, así como a causa de acontecimientos sobre los que no puede influir Milla.Travel, puedan producirse anomalías o la suspensión pasajera de los servicios del sitio web.</div><br>

      <div><strong>16. MANTENIMIENTO DE DATOS</strong> Milla.Travel no pretende ser un almacén de datos a prueba de fallas o una solución de respaldo de datos. En el caso de cualquier pérdida o corrupción de los datos del usuario suscrito, las transacciones utilizarán sus esfuerzos comercialmente razonables para restaurar los datos del cliente perdidos o dañados de la última copia de seguridad de dichos datos mantenida por el equipo de desarrollo. El cliente reconoce que la restauración completa de sus datos puede no ser posible en todas las circunstancias.</div><br>

      <div><strong>17. POLITICA DE COOKIES</strong> El sitio web requiere algunas cookies estrictamente necesarias para funcionar. Los datos almacenados en estas cookies son únicamente utilizados para personalizar la experiencia y para mantener las sesión de los usuarios. Adicionalmente, los servicios de Trengo, Google Analytics y Google AdSense presentes en milla utilizan cookies para la recogida de información estadística y analítica.</div><br>

      <div><strong>18. INICIO DE SESIÓN CON GOOGLE</strong> Al utilizar el botón de google para iniciar sesión, se recopilará y guardará el nombre, apellido, email e identificador en google desde la cuenta con el propósito de acceder y personalizar el servicio en milla. Esta información no será compartida con terceros.</div><br>

      <div><strong>19. DURACIÓN Y TERMINACIÓN</strong> La presentación de los servicios que Milla.Travel proporciona a través del sitio web tiene, en principio, una duración indefinida. No obstante, Milla.Travel está autorizada para dar por terminada o suspender la prestación de sus servicios en cualquier momento, sin perjuicio de lo que se hubiere dispuesto al respecto en las correspondientes condiciones particulares. En cualquier caso, Milla.Travel advertirá previamente la terminación o la suspensión de cualquier servicio o de la totalidad de los mismos a los usuarios.</div><br>

      <div><strong>20. ACEPTACION DE TÉRMINOS Y CONDICIONES</strong> El usuario comprende que la utilización del sitio web y la contratación de los servicios requiere de la aceptación de los presentes Términos y Condiciones. Milla.Travel se reserva el derecho de modificar estos Términos y Condiciones, publicándolos directamente en su sitio web, lo que en caso alguno afectará los derechos válidamente adquiridos y servicios contratados por los Usuarios al amparo de la versión entonces vigente de los Términos y Condiciones. Los Términos y Condiciones han sido actualizados por última vez con fecha 16 de Diciembre de 2019. Cualquier modificación será reflejada en versiones futuras de estos “Términos y Condiciones,” y será publicada en esta página, por lo que se aconseja revisarlos periódicamente.</div><br>

      <div><strong>21. LEGISLACION APLICABLE Y JURISDICCION</strong> Los presentes Términos y Condiciones de Milla.Travel se regirán por la legislación chilena.</div><br>
    </div>
  </div>
</template>

<style scoped>
.terms {
  max-width: 960px;
  width: 100%;
  margin: 0 auto;
  margin-top: 80px;
  text-align: center;
}

.text-left {
  text-align: left;
}

.terms__terms {
  text-align: justify;
  padding: 0 32px;
}
</style>